movieproject/movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'
urlpatterns = [

    path('',views.home,name='home'),
    path('movie/<int:movie_id>',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:movie_id>',views.update,name='update'),
    path('delete/<int:movie_id>',views.delete,name='delete')
]

movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here
class movie(models.Model):
    name=models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')
    def __str__(self):
        return self.name

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
# Create your views here.
from . models import movie
from . form import mform


def home(request):
    movieobj = movie.objects.all()
    context ={
        'movie_list': movieobj
                }
    return render(request,'index.html',context)
def detail(request,movie_id):
    Movie = movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'Movie':Movie})
def add_movie(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        Movie= movie(name=name,desc=desc,year=year,img=img)
        Movie.save()

    return render(request,'add.html')
def update(request,movie_id):
    Movie = movie.objects.get(id=movie_id)
    form = mform(request.POST or None,request.FILES,instance=Movie)
    if form.is_valid():
        form.save()
        return redirect('/')

    return render(request,'edit.html',{'form':form,'movie':Movie})
def delete(request,movie_id):
    if request.method == 'POST':
        Movie = movie.objects.get(id=movie_id)
        Movie.delete()
        return redirect('/')
    return  render(request,'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
     {% csrf_token %}
    <input type="text" name="name" placeholder="Enter movie"><br>
    <input type="text" name="desc" placeholder="Enter Description"><br>
    <input type="text" name="year" placeholder="Enter year"><br>
    <input type="file" name="img" ><br>
    <input type="submit">
</form>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>movie</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">    <link rel = "stylesheet" href = "https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet"  href="{% static 'style.css' %}">
</head>
<body >
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
      Online Movie Store
  </a>
</nav>
{% block body %}
{% endblock %}

</body>
</html>

movieproject/templates/delete.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    Are you sure to delete this movie??
    <input type="submit">

</form>

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{Movie.img.url}} " width="300" height="300">
        </div>
        <div class="col-md-6" >
            <h3> {{Movie.name}}</h3>
            <h4> {{Movie.desc}}</h4>
            <h4> {{Movie.year}}</h4>
            <a class="btn btn-warning" href="{% url 'movieapp:update' Movie.id %}">Update</a>
            <a  class="btn btn-danger" href="{% url 'movieapp:delete' Movie.id %}">Delete</a>
        </div>
    </div>

</div>
    {% endblock %}

movieproject/templates/edit.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}<br>
    <input type="submit">
</form>

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-sm-4 col-md-4 col-lg-4">
               <div class="card">
               <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" height="250px">
               <div class="card-body">
                <h5 class="card-title">{{i.name}}</h5>
               <p class="card-text">{{i.desc}}</p>
               <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">view details</a>
         </div>
</div>

        </div>
 {% endfor %}
    </div>

</div>

{% endblock %}